<?php

namespace Database\Seeders;

use App\Models\Assignment;
use App\Models\Course;
use App\Models\Subject;
use App\Models\User;
use Faker\Factory;
use Illuminate\Database\Seeder;
use Illuminate\Support\Arr;
use Illuminate\Support\Carbon;

class AssignmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = Factory::create();

        $titles =
            [
                'The Art of Curiosity: Unveiling the Unknown',
                'The Soundscape of Silence: Exploring Noiseless Environments',
                'Journey Through Forgotten Realms: Rediscovering Lost Histories',
                'Beyond the Frame: Exploring Multidimensional Art',
                'The Magic of Micromovements: Unraveling Subtle Gestures',
                'The Language of Dreams: Decoding Symbolic Meanings',
                'Sculpting with Shadows: Unveiling Hidden Forms',
                'The Science of Synchronicity: Understanding Meaningful Coincidences',
                'From Trash to Treasure: Transforming Waste into Art',
                'The Essence of Emptiness: Exploring Negative Space',
                'The Art of Illusion: Deconstructing Optical Tricks',
                'Echoes of Nature: Capturing Environmental Sounds',
                'The Power of Absurdity: Embracing Nonsense in Creativity',
                'Virtual Voyages: Exploring Immersive Digital Environments',
                'Designing for Inclusivity: Creating Accessible Spaces',
                'The Alchemy of Colors: Blending Pigments and Emotions',
                'From Dystopia to Utopia: Redesigning Societal Systems',
                'The Rhythm of Life: Exploring Patterns in Nature',
                'The Power of Silence: Embracing Stillness in Communication',
                'Forging New Frontiers: Innovating with Unconventional Materials',
                'The Poetry of Mathematics: Discovering Beauty in Numbers',
                'The Art of Disguise: Unveiling Hidden Identities',
                'Building Bridges: Fostering Cultural Exchange through Art',
                'The Dance of Light: Harnessing Illumination in Design',
                "Unlocking the Mind's Eye: Exploring Imaginative Visualization",
                'The Language of Machines: Decoding Binary Communication',
                'Embracing Chaos: Exploring Randomness in Creativity',
                'From Analog to Digital: Transforming Traditional Media',
                'The Aesthetics of Imperfection: Finding Beauty in Flaws',
                'The Intersection of Art and Science: Exploring the Synthesis',
                "Nature's Symphony: Composing Music Inspired by the Environment",
                'The Unseen World: Revealing Microscopic Wonders',
                'The Art of Surrender: Letting Go for Creative Breakthroughs',
                'Redefining Boundaries: Exploring Transcultural Art Movements',
                'The Harmony of Contrast: Balancing Opposing Elements',
                'The Power of Reflection: Unveiling Inner Truths',
                'Mapping Memories: Exploring Personal Geographies',
                'Disruptive Innovation: Challenging Norms through Design',
                'The Art of Mindfulness: Cultivating Present-Moment Awareness',
                'The Evocative Object: Infusing Emotion into Design',
                'Stepping into Shadows: Exploring Noir Photography',
                'Coding Creativity: Blending Art and Technology',
                'Embracing the Unknown: Exploring Uncertainty in Art',
                'The Poetics of Space: Transforming Environments through Design',
                'The Language of the Body: Expressing Emotion through Movement',
                'The Paradox of Simplicity: Unveiling Profound Minimalism',
                'Merging Realities: Exploring Augmented and Virtual Spaces',
                'The Art of Repair: Transforming Brokenness into Beauty',
                'The Power of Narrative: Crafting Compelling Visual Stories',
                'The Fragility of Time: Capturing Transience in Photography',
                'From Sound to Silence: Exploring the Power of Rest',
                'The Hybrid Aesthetic: Blending Traditional and Digital Art',
                'The Multisensory Experience: Engaging All Senses in Design',
                'The Art of Serendipity: Embracing Accidental Discoveries',
                'The Abstract Gaze: Reimagining Reality through Abstraction',
                'Unconventional Materials: Exploring Art beyond the Canvas',
                'The Symmetry of Nature: Discovering Patterns in the World',
                'The Poetic Mind: Exploring Creativity through Stream of Consciousness',
                'The Art of Adaptation: Responding to Changing Environments',
                'The Impermanent Installation: Embracing Ephemeral Art',
                'The Architecture of Emotion: Designing Spaces for Psychological Well-being',
                'The Essence of Movement: Capturing Dynamics in Sculpture',
                'The Digital Dilemma: Exploring the Impact of Technology on Creativity',
                'The Art of Contradiction: Embracing Paradoxical Concepts',
                'The Intersection of Sound and Space: Creating Sonic Installations',
                'From Chaos to Order: Exploring the Power of Organization',
                'The Art of Perception: Shifting Perspectives through Visual Illusions',
                'The Language of Typography: Communicating Meaning through Fonts',
                'The Nature of Transformation: Exploring Metamorphosis in Art',
                'The Beauty of Decay: Capturing Transient Moments in Photography',
                'The Organic Abstraction: Exploring Nature-inspired Art',
                'The Intuitive Process: Embracing Spontaneity in Creativity',
                'The Art of Collaboration: Fostering Collective Expression',
                'The Fluidity of Gender: Exploring Identity through Art',
                'The Architecture of Light: Illuminating Spaces with Design',
                'The Ethereal Landscape: Capturing Otherworldly Scenes',
                'The Power of Subversion: Challenging Social Norms through Art',
                'The Material Metaphor: Exploring Symbolism in Sculpture',
                'The Algorithmic Canvas: Creating Art through Code',
                'The Unspoken Language: Expressing Emotion through Abstract Art',
                'The Intricacy of Nature: Examining Patterns in the Organic World',
                'The Transformative Power of Sound: Creating Sonic Environments',
                'The Art of Transcendence: Exploring Spiritual Themes',
                'The Narrative of Objects: Unveiling Personal Histories',
                'The Fluid Aesthetic: Blending Art and Science',
                'The Embrace of Vulnerability: Expressing Authenticity through Art',
                'The Ecology of Design: Creating Sustainable Solutions',
                'The Architecture of Memory: Constructing Personal Narratives',
                'The Unseen Dimensions: Revealing Hidden Realities',
                'The Experiential Installation: Engaging Viewers in Interactive Art',
                'The Beauty of Impermanence: Capturing Fleeting Moments',
                'The Essence of Movement: Expressing Energy through Dance',
                'The Digital Surreal: Exploring Surrealism in the Digital Age',
                'The Art of Ritual: Transforming Everyday Actions into Meaningful Gestures',
                'The Alchemy of Materials: Exploring Transformation in Art',
                'The Poetry of Mathematics: Exploring Mathematical Concepts in Art',
                'The Intersection of Nature and Technology: Blurring Boundaries',
                'The Unseen Forces: Revealing the Invisible in Nature',
                'The Language of the Subconscious: Exploring Dreamscapes',
                'The Poetics of Architecture: Designing Spaces for Human Connection',
                'The Intertwined Universe: Exploring Interconnectedness in Art',
                'The Kinetic Experience: Engaging Viewers through Movement',
                'The Materiality of Light: Sculpting with Illumination',
                'The Essence of Transience: Capturing Fleeting Beauty in Photography',
                'The Art of Serenity: Exploring Calmness and Stillness in Art',
                'The Synthetic Aesthetic: Redefining Nature through Synthetic Art',
                'The Transformative Power of Color: Embracing Chromatic Vibrancy',
                'The Architecture of Dreams: Designing Imaginary Spaces',
                'The Haunting Narratives: Exploring Ghostly Tales in Art',
                'The Harmony of Contrasts: Balancing Opposing Elements in Design',
                'The Fluid Identity: Exploring Self-expression through Multiple Perspectives',
                'The Interplay of Light and Shadow: Capturing Dramatic Contrasts',
                'The Poetics of Fragility: Revealing Vulnerability in Art',
                'The Dynamic Canvas: Exploring Movement and Action in Painting',
                'The Geometry of Nature: Examining Mathematical Patterns in the Organic World',
                'The Architecture of Dreams: Constructing Fantastical Spaces',
                'The Intersection of Art and Technology: Exploring Interactive Installations',
                'The Evocative Essence: Infusing Art with Emotional Resonance',
                'The Transcendent Soundscape: Creating Sonic Journeys',
                'The Art of Simplicity: Reducing Complexity for Powerful Impact',
                'The Metaphorical Metamorphosis: Transforming Symbolism into Art',
                'The Synthetic Nature: Exploring Artificial Ecosystems',
                'The Language of Nature: Communicating with the Organic World',
                'The Architecture of the Senses: Designing Sensorial Experiences',
                'The Sublime in Subtraction: Exploring Minimalism in Art',
                'The Aesthetics of Impermanence: Capturing Transitory Beauty',
                'The Narrative of Place: Weaving Stories through Landscapes',
                'The Alchemy of Sound: Transmuting Noise into Music',
                'The Digital Identity: Exploring Self-representation in the Digital Age',
                'The Exquisite Corpse: Collaborative Artistic Creation',
                'The Hybrid Aesthetic: Integrating Traditional and Digital Techniques',
                'The Intricate Web: Examining Connections in Nature and Society',
                'The Poetics of Decay: Finding Beauty in the Ephemeral',
                'The Architectural Narrative: Constructing Stories through Spaces',
                'The Luminary Canvas: Illuminating Art with Light',
                'The Geometry of Emotion: Mapping Feelings through Art',
                'The Experiential Journey: Guiding Viewers through Immersive Art',
                'The Aesthetics of Chaos: Embracing Disorder in Design',
                'The Dialogues of Silence: Exploring Silence as a Means of Communication',
                'The Altered Perception: Shifting Perspectives through Art',
                'The Nature of Sound: Exploring Sonic Landscapes',
                'The Abstract Essence: Expressing Essence through Non-representational Art',
                'The Architecture of Harmonious Living: Designing Sustainable Communities',
                'The Elemental Aesthetic: Exploring the Power of Earth, Fire, Water, and Air',
                'The Digital Anomalies: Distorting Reality through Digital Art',
                'The Art of Memory: Representing the Intangible',
                'The Evolution of Expression: Tracing Artistic Styles through History',
                'The Spatial Poetics: Expanding Narratives through Physical Environments',
                'The Intuitive Impulse: Embracing Spontaneous Creativity',
                'The Emergence of Identity: Exploring the Construction of Self through Art',
            ];

        foreach ($titles as $key => $title) {
            Assignment::create([
                'user_id' => User::teacher()->inRandomOrder()->value('id'),
                'subject_id' => Subject::inRandomOrder()->value('id'),
                'course_id' => Course::inRandomOrder()->value('id'),
                'title' => $faker->unique()->name(),
                'start_date' => Carbon::today()->subDays(rand(0, 25)),
                'end_date' => Arr::random([Carbon::today()->addDay(rand(1, 9)), Carbon::today()->subDays(rand(1, 9))]),
                'mark' => rand(50, 200),
                'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque ab ut doloremque, nam dolorem et maxime molestiae veniam corrupti. Necessitatibus doloremque sapiente, voluptates id doloribus veritatis obcaecati nesciunt omnis consequuntur?',
            ]);
        }
    }
}
